apiVersion: v1
kind: ConfigMap
metadata:
  name: proxy-config
  namespace: single-cell-genomics
data:
  AWS_REGION: "us-east-1"
  ENDPOINT1_SAGEMAKER_ENDPOINT_NAME: "assessment4-robert-endpoint1-flex"
  ENDPOINT2_SAGEMAKER_ENDPOINT_NAME: "assessment4-robert-endpoint2-xenium"
